### PR TITLE
Code Review Request --> Friendships v2

### PR DESCRIPTION
**Pull request by rammazzoti2000**
In this milestone, we implement friendships with 2 rows for mutual friendship.
 - We created  `has_many through` associations for User and Friendship models; this allows us to generate two rows in the `Friendship` table that can be checked by either **running the local server in the browser and creating a new friendship between two users and then check in `rails console` the generated friendship**, or directly in `rails console` by using as follows:
        * `User.create(name: 'one', email: 'one@example.com', password:'microverse')`
        * `User.create(name: 'two', email: 'two@example.com', password:'microverse')`
        * `Friendship.create(user_id: `_id_of_user_one_`, friend_id: `_id_of_user_two_`, confirmed: true)`
        * `Friendship.create(user_id: `_id_of_user_two_`, friend_id: `_id_of_user_one_`, confirmed: true)`
        * `Friendship.where(user_id: `_id_of_user_one_`)`
        * `Friendship.where(user_id: `_id_of_user_two_`)` ==> or,
        * `Friendship.all`
- All unit/integration tests passed.
#### Kindly waiting for your feedback :smile:

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work team! :rocket: 
Please check on this in a few minutes for some feedback!

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by nikasulo** [comment]
# Awesome job! @rammazzoti2000 and @vzdrizhni :medal_military: 
You have both done a really awesome job and your work looks so professional. Please consider that operations at the database level are always much faster than querying and sorting through ruby code in application memory and that being said, please consider my comments below, make the appropriate changes and request a re-review.

#### Friends and own posts 
Please consider the following method to curate the posts for the user feed.
screenshot

#### Inverted friendships and friend requests
Please consider the following way to define friend requests
screenshot

#### Pending friendships and pending friends
screenshot

#### Confirmed friendships and friends
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by rammazzoti2000** [comment]
> # Awesome job! @rammazzoti2000 and @vzdrizhni 
> You have both done a really awesome job and your work looks so professional. Please consider that operations at the database level are always much faster than querying and sorting through ruby code in application memory and that being said, please consider my comments below, make the appropriate changes and request a re-review.
> 
> #### Friends and own posts
> Please consider the following method to curate the posts for the user feed.
> screenshot
> 
> #### Inverted friendships and friend requests
> Please consider the following way to define friend requests
> screenshot
> 
> #### Pending friendships and pending friends
> screenshot
> 
> #### Confirmed friendships and friends
> screenshot
> 
> ##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

### Thank you for the valuable feedback, much appreciated :smile: 
All changes required by the previous TSE have been implemented, except for `inverted_friendship` that would mess up the friendship behaviour of the entire application, because of our helper methods already implement throughout the entire code, please don't count this against us :pray: 
####
~Also the stickler is enabled and as you can notice the code passed all the checks while the checks tab it says `Waiting for checks information...`, I really don't know why is doing that~

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work implementing the suggested changes :clap: However, some changes need to be applied in order to get approval for this milestone. Check :arrow_down: 

- **[REQUIRED]** The app show errors upon user registration, it's probably because it's fetching the timeline posts which are initially **nil**, add the necessary logic to avoid this problem.

* [x] when friendship is confirmed, an additional row with reversed user-friend pair is created

```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
  - You have a similar method in user model, plus it doesn't create the inverted friendship. I suggest using the method above instead.

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by rammazzoti2000** [comment]
> ### Great work implementing the suggested changes  However, some changes need to be applied in order to get approval for this milestone. Check 
> * **[REQUIRED]** The app show errors upon user registration, it's probably because it's fetching the timeline posts which are initially **nil**, add the necessary logic to avoid this problem.
> 
> * [x]  when friendship is confirmed, an additional row with reversed user-friend pair is created
> 
> ```ruby
> # Friendship model
> 
> def confirm_friend
>   self.update_attributes(confirmed: true)
>   Friendship.create!(friend_id: self.user_id,
>                   user_id: self.friend_id,
>                   confirmed: true)
> end
> ```
> 
> * You have a similar method in user model, plus it doesn't create the inverted friendship. I suggest using the method above instead.
> 
> ### That's it  When finished, kindly submit a code re-review request 
> Happy coding 
> **_Ahmed Mahfoudh_**

Thank you for the valuable feedback, much appreciated :smile:
All changes required by the previous TSE have been implemented, kindly waiting for your feedback.

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work implementing the suggested changes :clap: However, some issues need to be fixed in order to get approval for this milestone. Check :arrow_down: 

- **[REQUIRED]** All the specs should pass :heavy_check_mark: You have some tests that are failing. :pray: fix them

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by rammazzoti2000** [comment]
> ### Great work implementing the suggested changes  However, some issues need to be fixed in order to get approval for this milestone. Check 
> * **[REQUIRED]** All the specs should pass heavy_check_mark You have some tests that are failing. pray fix them
> 
> ### That's it  When finished, kindly submit a code re-review request 
> Happy coding 
> **_Ahmed Mahfoudh_**

### Ohh :hushed: totally forgot about those
Anyway now they are passing, give it another try, thanks :sweat_smile:

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thanks for the improvements you've done.
However, there are still things to change.

https://github.com/rammazzoti2000/ror-social-scaffold/blob/fca1f42d8394c7cc2a88f53f3458010b33def376/spec/feature/friendship_spec.rb#L6-L16
Even if it's working (because all your tests passed), that is not a good way to write tests. 
Please, change everything similar by using [Factory Bot](https://github.com/thoughtbot/factory_bot_rails). Read it, set it up and update your tests

Kindly make the changes and submit a new code review request.
Thanks

Mael FOSSO

**Comment by rammazzoti2000** [comment]
> # Changes required 
> Hello,
> 
> Thanks for the improvements you've done.
> However, there are still things to change.
> 
> https://github.com/rammazzoti2000/ror-social-scaffold/blob/fca1f42d8394c7cc2a88f53f3458010b33def376/spec/feature/friendship_spec.rb#L6-L16
> 
> 
> Even if it's working (because all your tests passed), that is not a good way to write tests.
> Please, change everything similar by using [Factory Bot](https://github.com/thoughtbot/factory_bot_rails). Read it, set it up and update your tests
> Kindly make the changes and submit a new code review request.
> Thanks
> 
> Mael FOSSO

## :rage:  Factory Bot is not  a requirement, but Rspec and Capybara is :bangbang: And we meet all requirements, stop asking us for changes
By the changes required of the previous TSE(@maelfosso ) we tried as best as we could to use Factory Bot to refactor out tests, but lets be honest, there is no explanation why our tests shouldn't be written like that.

**Review by Forison — APPROVED** [review]
## Status:: Approved✔️
## 🙋‍♂️ team,
You have come a long way on this one and I saw your previous comments, sorry about that.
I agree with you when you say Factory_bot or factory_girl was not a requirement💯.
 One good thing about factory_bot is that it allows you to test out your models and code without touching your database. This I know is quite an efficient way of testing. There are other importance associated with it as well😌.
Sorry for earlier maybe it should have come as a suggestion🤗.
On the bright side, you went ahead to implement it, definitely, you learned something🤗
Thank you
### See you in the next task
#### Happy coding
Addo

**Pull request merged**
